<form class="connect" role="connection" action="index.php?page=user" method="POST">
<div class="text-center" style="padding:50px 0">
	<div class="logo">LOGIN</div>
	<div class="login-form-1">
		<form id="login-form" class="text-left" method="POST">
			<div class="login-form-main-message"></div>
			<div class="main-login-form">
				<div class="login-group">
					<div class="form-group">
						<label for="login" class="sr-only">Login</label>
						<input type="text" class="form-control" id="login" name="login" placeholder="login">
					</div>
					<div class="form-group">
						<label for="password" class="sr-only">Password</label>
						<input type="password" class="form-control" id="password" name="password" placeholder="password">
					</div>
					<input type="hidden" name="action" value="login">
					<input type="submit" value="VALIDER">
				</div>
			</div>
		</form>
	</div>
</div>
</form>