<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

<div class="text-center" style="padding:50px 0">
	<div class="logo">REGISTER</div>
	<div class="login-form-1">
		<form id="register-form" class="text-left" method="POST">
			<div class="login-form-main-message"></div>
			<div class="main-login-form">
				<div class="login-group">
					<div class="form-group">
						<label for="login" class="sr-only">login</label>
						<input type="text" class="form-control" id="reg_username" name="login" placeholder="login">
					</div>
					<div class="form-group">
						<label for="password1" class="sr-only">Password</label>
						<input type="password" class="form-control" id="password1" name="password1" placeholder="password">
					</div>
						<div class="form-group">
						<label for="password2" class="sr-only">Password</label>
						<input type="password" class="form-control" id="password2" name="password2" placeholder="password">
					</div>
					<input type="hidden" name="action" value="create">
					<input type="submit" value="VALIDER">
				</div>
			</div>
		</form>
	</div>
</div>