<!DOCTYPE html>
<html>
    <head>
        <title>Tchat</title>
        <link href="public/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
        <script src="public/js/jquery-1.11.0.min.js"></script>
        <link href="public/css/style.css" rel="stylesheet" type="text/css" media="all" />  
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
     
        <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
        <script type="text/javascript" src="public/js/easing.js"></script>
        
        <link href="public/css/memenu.css" rel="stylesheet" type="text/css" media="all" />
        <script type="text/javascript" src="public/js/memenu.js"></script>
        <script src="./public/js/bootstrap.min.js"></script>
        <script src="./public/js/script.js"></script>
    </head>
	<body>
		<?php require('apps/header.php'); ?>
		<?php require('apps/content.php'); ?>
		<?php require('apps/footer.php'); ?>
	</body>
</html>